TT-9099 convert from mocha to jest
sealink/printers_qt pull request #415
Opened 2021-03-23 04:12 UTC by Damon1024

### WHY
To keep frameworks consistent, need to convert from Mocha to Jest

2021-03-23 23:39 UTC, HellRok approved these changes

2021-03-24 21:27 UTC, jmortlock approved these changes

2021-03-24 21:32 UTC, jmortlock commented
Hi @Damon1024 I rebased this to fix the merge conflicts and I noticed a couple more things that need changing.

Can you please convert Sinon over to Jest.Mock
Can you also please remove Chai

Thanks

2021-03-24 21:32 UTC, jmortlock requested changes
Remove Chai / Sinon

2021-03-25 00:55 UTC, closed without merging